services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx-proxy/cert/:/etc/nginx/certs/
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"

  php:
    build: ./docker/php
    restart: on-failure
    volumes:
      - .:/home/app
      - ./docker/php/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    tty: true
    external_links:
      - nginx-proxy:first-microservice.docker
    environment:
      VIRTUAL_HOST: first-microservice.docker
      VIRTUAL_PORT: 8080
      CERT_NAME: default
    expose:
      - "8080"

  db:
    image: mariadb:10.11
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - .:/home/app
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - web

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    networks:
      - web
    environment:
      VIRTUAL_HOST: rabbitmq.first-microservice.docker
      VIRTUAL_PORT: 15672
      CERT_NAME: default

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
